name: Reservation

on:
  schedule:
    - cron: "0 3 * * 4"
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // Get a list of open issues
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
            })
            const issues = await github.paginate(opts)

            for (const issue of issues) {
              console.log(issue.title)
            }
