name: Update

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // Get a list of open issues
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
            })
            const issues = await github.paginate(opts)

            const issue = issues.find(issue => issue.title === 'Testing test')

            console.log(issue.title)
            console.log(issue.id)
